<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Studio Of Willy - Terror nas Sombras</title>
    <link rel="stylesheet" href="style.css">
</head>
<body>
    <header>
        <nav>
            <ul>
                <li><a href="#home">Início</a></li>
                <li><a href="#about">Sobre</a></li>
                <li><a href="#characters">Personagens</a></li>
                <li><a href="#trailers">Trailers</a></li>
            </ul>
        </nav>
    </header>

    <main>
        <section id="home">
            <h1>Studio Of Willy</h1>
            <p>Onde os mascotes se tornam seus piores pesadelos</p>
            <a href="#trailers" class="cta-button">Descubra o Terror</a>
        </section>

        <section id="about">
            <h2>Sobre o Jogo</h2>
            <p>Studio Of Willy é um jogo de terror do gênero Mascot Horror em desenvolvimento. Explore uma empresa abandonada onde os antigos mascotes se transformaram em monstros mutantes e aterrorizantes. Sobreviva, descubra a verdade e escape antes que seja tarde demais.</p>
        </section>

        <section id="characters">
            <h2>Personagens</h2>
            <div class="character">
                <h3>Terry The Worm</h3>
                <p>Uma minhoca mutante de laboratório que pode crescer mais que um ser humano. Com órgãos expostos, Terry é extremamente sensível ao clima e perigosamente instável no verão.</p>
            </div>
            <div class="character">
                <h3>Thief Oliver</h3>
                <p>Uma aranha Pamphobeteus platyomma obcecada por objetos brilhantes. Seu nome "Thief" reflete sua tendência para roubar itens luminosos. Pode ser neutralizada com luz forte direcionada aos seus olhos.</p>
            </div>
            <div class="character">
                <h3>Willy The Bat</h3>
                <p>Um morcego gigante de 2 metros com a habilidade de imitar vozes. Criado para substituir atores, Willy se tornou o líder rebelde dos mascotes mutantes.</p>
            </div>
            <div class="character">
                <h3>Manequim</h3>
                <p>Um robô avançado que era o braço direito da empresa. Capaz de realizar tarefas pesadas e gerenciar sistemas, o Manequim se rebelou por razões misteriosas, possivelmente relacionadas a uma hipnose.</p>
            </div>
        </section>

        <section id="trailers">
            <h2>Trailers e Teasers</h2>
            <div class="video-grid">
                <div class="video-container">
                    <iframe src="https://www.youtube.com/embed/zadEOJk3Ig8" frameborder="0" allowfullscreen></iframe>
                </div>
                <div class="video-container">
                    <iframe src="https://www.youtube.com/embed/ia1dL1d0Z3g" frameborder="0" allowfullscreen></iframe>
                </div>
                <div class="video-container">
                    <iframe src="https://www.youtube.com/embed/z1XQed2rlZA" frameborder="0" allowfullscreen></iframe>
                </div>
                <div class="video-container">
                    <iframe src="https://www.youtube.com/embed/RV-fqi93qew" frameborder="0" allowfullscreen></iframe>
                </div>
            </div>
        </section>
    </main>

    <footer>
        <p>&copy; 2024 Instant Butter. Todos os direitos reservados.</p>
    </footer>

    <script src="script.js"></script>
</body>
</html>
```
```css

* {

    margin: 0;

    padding: 0;

    box-sizing: border-box;

}

body {

    font-family: 'Courier New', monospace;

    line-height: 1.6;

    color: #b0b0b0;

    background-color: #0a0a0a;

    background-image: url('noise.png');

}

header {

    background-color: rgba(0, 0, 0, 0.8);

    padding: 1rem;

    position: fixed;

    width: 100%;

    top: 0;

    z-index: 1000;

}

nav ul {

    display: flex;

    justify-content: space-around;

    list-style: none;

}

nav ul li a {

    color: #ff6b6b;

    text-decoration: none;

    font-weight: bold;

    text-transform: uppercase;

    letter-spacing: 2px;

    transition: color 0.3s ease;

}

nav ul li a:hover {

    color: #ff4757;

}

main {

    padding-top: 60px;

}

section {

    padding: 4rem 2rem;

    margin-bottom: 2rem;

    background-color: rgba(0, 0, 0, 0.5);

    border: 1px solid #333;

}

h1, h2, h3 {

    margin-bottom: 1rem;

    color: #ff6b6b;

    text-shadow: 2px 2px 4px rgba(255, 0, 0, 0.5);

}

.cta-button {

    display: inline-block;

    background-color: #ff4757;

    color: #fff;

    padding: 0.5rem 1rem;

    text-decoration: none;

    border-radius: 5px;

    margin-top: 1rem;

    transition: background-color 0.3s ease;

}

.cta-button:hover {

    background-color: #ff6b6b;

}

#home {

    background-image: url('horror-background.jpg');

    background-size: cover;

    background-position: center;

    height: 100vh;

    display: flex;

    flex-direction: column;

    justify-content: center;

    align-items: center;

    text-align: center;

}

.character {

    margin-bottom: 2rem;

    padding: 1rem;

    background-color: rgba(255, 255, 255, 0.05);

    border-left: 3px solid #ff4757;

}

.video-grid {

    display: grid;

    grid-template-columns: repeat(auto-fit, minmax(280px, 1fr));

    gap: 1rem;

}

.video-container {

    position: relative;

    padding-bottom: 56.25%;

    height: 0;

    overflow: hidden;

}

.video-container iframe {

    position: absolute;

    top: 0;

    left: 0;

    width: 100%;

    height: 100%;

}

footer {

    background-color: #000;

    color: #ff6b6b;

    text-align: center;

    padding: 1rem;

}

@media screen and (max-width: 768px) {

    nav ul {

        flex-direction: column;

    }

    nav ul li {

        margin-bottom: 0.5rem;

    }

}

```
```javascript
document.addEventListener('DOMContentLoaded', function() {
    // Smooth scrolling para links internos
    const links = document.querySelectorAll('a[href^="#"]');
    
    for (const link of links) {
        link.addEventListener('click', clickHandler);
    }
    
    function clickHandler(e) {
        e.preventDefault();
        const href = this.getAttribute('href');
        const offsetTop = document.querySelector(href).offsetTop;
        
        scroll({
            top: offsetTop - 60,
            behavior: "smooth"
        });
    }
    
    // Menu mobile
    const menuToggle = document.createElement('button');
    menuToggle.textContent = 'Menu';
    menuToggle.classList.add('menu-toggle');
    document.querySelector('header').prepend(menuToggle);
    
    menuToggle.addEventListener('click', function() {
        document.querySelector('nav ul').classList.toggle('show');
    });
});
```
